### Import the required libraries.

In [5]:
import pandas as pd

### Load the Dataset called customer_churn_training.csv.

In [10]:
data = pd.read_csv("customer_churn_training.csv")

In [7]:
data.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [8]:
data.shape

(440833, 12)

### The dataset contains the 4,40,833 observation with 12 columns.

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

#### Only one observation contains the null value.

In [11]:
data.isna().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [12]:
data[data.isna().any(axis=1)]

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
199295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data = data.dropna()

#### The null value was droped because no record was entered.

In [24]:
data.dtypes

CustomerID           float64
Age                  float64
Gender                object
Tenure               float64
Usage Frequency      float64
Support Calls        float64
Payment Delay        float64
Subscription Type     object
Contract Length       object
Total Spend          float64
Last Interaction     float64
Churn                float64
dtype: object

### -----------------------------------DataTypes convertion-----------------------------------
##### The column Total Spend contains the float values and remaining columns can be converted as integer.

In [26]:
data.columns.to_list()

['CustomerID',
 'Age',
 'Gender',
 'Tenure',
 'Usage Frequency',
 'Support Calls',
 'Payment Delay',
 'Subscription Type',
 'Contract Length',
 'Total Spend',
 'Last Interaction',
 'Churn']

In [ ]:
int_col = ['CustomerID','Age','Tenure','Usage Frequency','Support Calls','Payment Delay','Last Interaction','Churn'] 

data[int_col] = data[int_col].astype(int)

In [30]:
data.dtypes

CustomerID             int64
Age                    int64
Gender                object
Tenure                 int64
Usage Frequency        int64
Support Calls          int64
Payment Delay          int64
Subscription Type     object
Contract Length       object
Total Spend          float64
Last Interaction       int64
Churn                  int64
dtype: object

#### 'CustomerID'---'Age'---'Tenure'---'Usage Frequency'---'Support Calls'---'Payment Delay'---'Last Interaction'---'Churn' This columns are converted to integer.

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 440832 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  int64
 1   Age                440832 non-null  int64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  int64
 4   Usage Frequency    440832 non-null  int64
 5   Support Calls      440832 non-null  int64
 6   Payment Delay      440832 non-null  int64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  int64
 11  Churn              440832 non-null  int64
dtypes: float64(1), int64(8), object(3)
memory usage: 43.7+ MB

In [33]:
data.shape

(440832, 12)

### Now the dataset was cleaned and no null values are present.

#### Check the dataset for duplicated values.

In [35]:
data.duplicated().sum()

np.int64(0)

In [36]:
data.to_csv("customer_churn_cleaned.csv",index=False)

### The Cleaned Dataset is saved.